<?php

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
?>

<div id="header"
     class="relative z-50 w-full"
     @keydown.window.escape="searchOpen = false;"
>
    <div class="container rs-mega-menu">
        <!--Main Navigation-->
        <div class="rs-mega-menu__wrapper  sections nav-sections ">
            <div class="off-canvas-menu-img rs-mega-menu__logo">
                <?= $block->getChildHtml('logo-burger'); ?>
            </div>
            <div class="rs-mega-menu__content page-main section-item-content nav-sections-item-content relative"
                 :class="{'max-h-screen overflow-hidden' : isLoading}"
            >
                <?= $block->getChildHtml('rs-topmenus') ?>
            </div>

            <div x-show="isLoading" class="rs-mega-menu__loader loader">
                <?= $block->getChildHtml('loader') ?>
            </div>
        </div>
    </div>
</div>

<script>
    document.querySelector('[data-action="toggle-nav"]').addEventListener('click', () => {
        window.dispatchEvent(new CustomEvent('load-mobile-menu'));
    })
</script>
