<!--We can use this context to add some thing in future-->
<?php
    /** @var \Rostilos\Base\Helper\Data  $baseHelper */
    $baseHelper = $this->helper('Rostilos\Base\Helper\Data');
    $enableAnimateCSS = (int) $baseHelper->getConfigValue('rostilos_general/general/enable_animate_css');
    $enableFontAwesome = (int) $baseHelper->getConfigValue('rostilos_general/general/enable_font_awesome');

    $autoHideMessage = (bool) $baseHelper->getConfigValue('rostilos_general/general/auto_hide_message');
    $messageTimeout = (int) $baseHelper->getConfigValue('rostilos_general/general/message_timeout');

    if($enableAnimateCSS) {
        /** @var \Magento\Framework\View\Element\Template $block */
        $href = trim($block->getViewFileUrl("Rostilos_Base::css/animate.min-4.1.1.css"));
        echo '<link rel="stylesheet" type="text/css" href="'. $href .'">';
    }
    if($enableFontAwesome) {
        /** @var \Magento\Framework\View\Element\Template $block */
        $href = trim($block->getViewFileUrl("Rostilos_Base::css/font-awesome.min-5.14.0.css"));
        echo '<link rel="stylesheet" type="text/css" href="'. $href .'">';
    }
?>

<script type="text/javascript">
    // Global variables
    let ubAjaxCartOptions = {};
    const AUTO_HIDE_MESSAGE = <?= ($autoHideMessage) ? 1 : 0; ?>;
    const MESSAGE_TIMEOUT = <?= ($messageTimeout) ? $messageTimeout : 5000; ?>;
</script>

